### ISSUE TITLE
Non-repeatable test for Student name in classroom_show_spec.rb

### ISSUE THREAD

**Issue by zoebisch** [learn-co-curriculum/while-and-until-looping-readme#6]
What I believe is an unintended consequence of using Faker::Name.name is that it occasionally generates an apostrophe in the name.  In the way the form gets rendered, the apostrophe becomes an alt-code like so:

       +  <li>
       +    Name: Bria O&#39;Connell
       +  </li>       

Diff:
       @@ -1,2 +1,67 @@

       -Bria O'Connell

While I am not certain this isn't intentional, it is a non-repeatable test. 

RSpec.describe "classroom_show_view" do
  let(:classroom) { Classroom.create(course_name: 'Math', semester: "Spring #{Time.now.year}") }
  let(:student){ Student.create(name: 'Bobby', hometown: Faker::Address.city, birthday: Faker::Date.between(25.years.ago, 18.years.ago)) }

  before do
    5.times do
      **Student.create(name: Faker::Name.name,** hometown: Faker::Address.city, birthday: Faker::Date.between(25.years.ago, 18.years.ago))
    end

**Comment by sgharms** [comment]
@zoebisch This is a very good insight and [often discussed](https://github.com/stympy/faker/issues/615). But it seems like this PR is opened on the wrong repository. Can you open this issue on some repo with a `classroom_show_view` spec?

Thanks!

**Comment by zoebisch** [comment]
Ahh, not sure how that happened! Issue raised here:

[https://github.com/learn-co-curriculum/simple-partials-lab/issues/5]

**Comment by sgharms** [comment]
Thanks for the update, we'll slot this work amongst our next set of
initiatives.
